### ISSUE TITLE
BubbleSorter

### ISSUE THREAD

**Issue by alebar** [alebar/fundamentals#1]
1. Create package `com.benko.exercise.sort`
2. In that package create two clases:
* `SortingApp` - class with the `main` method, an entry point for the application
* `BubbleSorter` - having method called `sort` that implements the bubble sort algorithm

The main method should:
* create an array of integers (can be hardcoded),
* create an instance of the `BubbleSorter`
* sort the array by invoking the `BubbleSorter#sort()` method of the sorter instance, and
* print sorted array to the standard output.

The declaration of the `sort` method should be:
```
void sort(int[] numbers)
```

**Comment by robertbenko** [comment]
Hi Alek ;)

I am pushing this forward hope so and
one question:
- when I declare `void sort(int[] numbers)` in BubbleSorter class I have to give an argument `numbers` from the main class using `BubbleSorter.sort(numbers)` I am wondering how to invoke it without an argument using `BubbleSorter#sort()` ?

**Comment by alebar** [comment]
'BubbleSorter#sort()' was a shortcut: I just wanted to name the method.
The full (and correct) declaration is below: having the 'numbers' argument.

**Comment by robertbenko** [comment]
OK good, please check.
